[package]
name = "mkwebfont"
version = "0.1.0"
edition = "2021"

[features]
default = ["clap"]

[[bin]]
name = "mkwebfont"
required-features = ["clap"]

[dependencies]
allsorts = "0.14"
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"], optional = true }
serde = { version = "1.0", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
