[package]
name = "mkwebfont"
version = "0.1.0"
authors = ["Lymia Kanokawa <lymia@lymia.moe>"]
edition = "2021"

description = "A library for creating compact sets of enums."
keywords = ["fonts"]
categories = ["command-line-utilities"]

repository = "https://github.com/Lymia/mkwebfont"
readme = "README.md"

license = "Apache-2.0"

exclude = [
    "contrib/woff2/brotli/docs",
    "contrib/woff2/brotli/tests",
    "contrib/woff2/brotli/java",
    "contrib/woff2/brotli/csharp",
    "contrib/woff2/brotli/js",
    "contrib/woff2/brotli/go",
]

[features]
default = ["binary", "bundled-harfbuzz"]
binary = ["clap", "tracing-subscriber"]
bundled-harfbuzz = ["hb-subset/bundled"]

[[bin]]
name = "mkwebfont"
required-features = ["binary"]

[dependencies]
anyhow = "1.0"
blake3 = "1.5"
brotli = { version = "4.0", features = ["ffi-api"] }
clap = { version = "4.5", features = ["derive"], optional = true }
hb-subset = "0.3"
roaring = "0.10"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"], optional = true }
unic-ucd-block = "0.9"

[build-dependencies]
cc = "1.0"
