[package]
name = "mkwebfont"
version = "0.1.0"
edition = "2021"

[features]
default = ["binary"]
binary = ["clap", "tracing-subscriber"]

[[bin]]
name = "mkwebfont"
required-features = ["binary"]

[dependencies]
allsorts = "0.14"
anyhow = "1.0"
brotli = { version = "3.5", features = ["ffi-api"] }
clap = { version = "4.5", features = ["derive"], optional = true }
lazy_static = "1.4"
roaring = "0.10"
serde = { version = "1.0", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"], optional = true }

[build-dependencies]
cc = "1.0"
