[package]
name = "mkwebfont"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "http2", "blocking"] }
serde_json = "1.0"
unic-ucd-category = "0.9"
