[package]
name = "mkwebfont_common"
version = "0.1.0"
authors = ["Lymia Kanokawa <lymia@lymia.moe>"]
edition = "2021"

description = "Internal crate for mkwebfont."
repository = "https://github.com/Lymia/mkwebfont"
license = "Apache-2.0"

[dependencies]
anyhow = "1.0"
bincode = "2.0.0-rc.3"
blake3 = { version = "1.5", features = ["pure"] }
tokio = { version = "1.37", features = ["rt-multi-thread"] }
tracing = "0.1"
wyrand = { git = "https://github.com/Lymia/wyrand-rs.git", features = ["wyhash", "v4_2"] } # low-usage crate, pin reviewed version
zstd = { version = "0.13", features = ["zstdmt"] }
