# Font splitting progresses in a few stages:
# - Stage 1: High priority font subsets are checked to see if they should be used.
# - Stage 2: The Google Fonts machine-learning based subset groups are checked to see if they should be used.
# - Stage 3: All remaining Google Fonts language groups should be checked to see if they are used
# - Stage 4: All remaining codepoints are divided into font files roughly based on Unicode blocks.

##########
# Stage 1

# The list of subsets to consider high-priority
high_priority_subsets = ["latin", "latin-ext"]

# The percentage of codepoints that must be present in a subset before it is emitted in this stage.
high_priority_ratio_threshold = 0.25

##########
# Stage 2

# The percentage of codepoints that must be present in a subset group before it is emitted in this stage.
accept_group_ratio_threshold = 0.25


##########
# Stage 3

# A subset must have at least this many codepoints *or* meet the ratio below to be emitted.
accept_subset_count_threshold = 20

# A subset must have at least this percentage of codepoints present to be emitted *or* meet the count above.
accept_subset_ratio_threshold = 0.1

##########
# Stage 4

# Any font subsets with less than this number of glyphs will not be generated, and instead will be combined into
# the residual Stage 4 subsets.
reject_subset_threshold = 20


# The maximum size for a residual subset made from codepoints not included in a Google Fonts subset.
residual_class_max_size = 200

# The preferred size for a residual subset made from codepoints not included in a Google Fonts subset.
residual_class_preferred_size = 100
