[package]
name = "mkwebfont_fontops"
version = "0.1.0"
authors = ["Lymia Kanokawa <lymia@lymia.moe>"]
edition = "2021"

repository = "https://github.com/Lymia/mkwebfont"

license = "Apache-2.0"

[dependencies]
